      - name: Clear Laravel config and cache
        run: |
          php artisan config:clear
          php artisan cache:clear
          php artisan route:clear
          php artisan view:clear
          composer dump-autoload -o
name: Railway Deploy & Migrate

name: Railway Deploy & Migrate

      # Railway akan otomatis deploy dari repo jika sudah terhubung
      # Jika ingin Railway CLI, tambahkan langkah berikut:
      # - name: Install Railway CLI
      #   run: npm install -g railway

      # - name: Deploy to Railway
      #   run: railway up
