name: Railway Deploy & Migrate

on:
  push:
    branches:
      - main

jobs:
  build-and-migrate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, bcmath, sqlite3

      - name: Install Composer dependencies
        run: composer install --no-interaction --prefer-dist --optimize-autoloader

      - name: Copy .env.example to .env
        run: cp .env.example .env

      - name: Generate app key
        run: php artisan key:generate

      - name: Run migrations and seeders
        run: php artisan migrate:fresh --seed

      # Railway akan otomatis deploy dari repo jika sudah terhubung
      # Jika ingin Railway CLI, tambahkan langkah berikut:
      # - name: Install Railway CLI
      #   run: npm install -g railway
      # - name: Deploy to Railway
      #   run: railway up
